using armbian-next matrix generator set targets as desired customize oci targets set CHECK_OCI=no default so no issues with looking at wrong OCI cache for artifact prep

diff --git a/.github/workflows/artifact-image-complete-matrix.yml b/.github/workflows/artifact-image-complete-matrix.yml
--- a/.github/workflows/artifact-image-complete-matrix.yml
+++ b/.github/workflows/artifact-image-complete-matrix.yml
@@ -5,8 +5,8 @@
 name: "artifact-image-complete-matrix"
 
 on:
-  schedule:
-    - cron: '0 1 * * *' # Scheduled runs every day at 2am UTC
+  #  schedule:
+  #    - cron: '0 1 * * *' # Scheduled runs every day at 2am UTC
   workflow_dispatch:
     inputs:
       skipImages:
@@ -22,7 +22,7 @@ on:
       checkOci:
         description: 'Check OCI for existing artifacts? yes = check OCI, no = always build everything'
         required: true
-        options: [ 'yes', 'no' ]
+        options: [ 'no', 'yes' ]
         type: choice
       skipCustomRepo:
         description: 'Skip custom repo? yes = skip custom repo, no = use custom repo'
@@ -48,11 +48,11 @@ env:
 
   # For easier reuse across the multiple chunks ('armbian/os' repo)
   USERPATCHES_REPOSITORY: "airframesio/airwaves-os"
-  USERPATCHES_REF: "matrix-reloaded" # branch or tag or sha1
+  USERPATCHES_REF: "main" # branch or tag or sha1
   USERPATCHES_DIR: "armbian/armbian-userpatches" # folder inside USERPATCHES_REPOSITORY
 
   # Armbian envs. Adjust to your needs.
-  # OCI_TARGET_BASE: "ghcr.io/${{ github.repository }}/" # This is picked up by the Docker launcher automatically. It does _not_ override the targets.yaml during info resolution.
+  OCI_TARGET_BASE: "ghcr.io/${{ github.repository }}/" # This is picked up by the Docker launcher automatically. It does _not_ override the targets.yaml during info resolution.
   DOCKER_ARMBIAN_BASE_COORDINATE_PREFIX: "ghcr.io/${{ github.repository }}:armbian-next-" # Use Docker image in same repo
   DOCKER_SKIP_UPDATE: "yes" # Do not apt update/install/requirements/etc during Dockerfile build, trust DOCKER_ARMBIAN_BASE_COORDINATE_PREFIX's images are up-to-date
 
@@ -387,3 +387,208 @@ jobs:
         if: always()
         run: |
           rm -rfv output/images userpatches/VERSION
+
+# template file: 750.single_repo.yaml
+
+  # ------ publish packages to repository -------
+
+  publish-debs-to-repo:
+    name: "publish debs to repo"
+    runs-on: [ "self-hosted", "Linux", 'armbian', "debs-to-repo" ]
+    if: ${{ !failure() && !cancelled() && (github.event.inputs.targetsFilterInclude == 'LEAVE_BRITNEY_ALONE') }} # eg: run if dependencies worked. See https://github.com/orgs/community/discussions/45058#discussioncomment-4817378
+    needs: [ "matrix_prep", "all-artifacts-ready" ]
+    steps:
+      # Prepare dependencies.
+      # If no /usr/bin/gpg, install gnupg2
+      # If no /usr/bin/reprepro, install reprepro
+      - name: Install dependencies
+        run: |
+          if [ ! -e /usr/bin/gpg ]; then
+            sudo apt-get update
+            sudo apt-get install -y gnupg2
+          fi
+          if [ ! -e /usr/bin/reprepro ]; then
+            sudo apt-get update
+            sudo apt-get install -y reprepro
+          fi
+
+      # Login to ghcr.io, for later uploading rootfs to ghcr.io
+      - name: Docker Login to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: "${{ github.repository_owner }}" # GitHub username or org
+          password: ${{ secrets.GITHUB_TOKEN }}    # GitHub actions builtin token. repo has to have pkg access.
+
+      # cleanup the place where we will clone the userpatches repo, to avoid git going insane and cleaning everything later
+      - name: Cleanup userpatches repo
+        if: ${{ ( env.USERPATCHES_REPOSITORY != '' ) && ( env.USERPATCHES_REF != '' ) }}
+        run: rm -rf userpatches.repo
+
+      - name: Checkout build repo
+        uses: actions/checkout@v3 # We don't need to clone git, really. A wget would suffice for GH-hosted runners. But using clone is better for Igor-hosted runners.
+        with:
+          repository: ${{ env.BUILD_REPOSITORY }}
+          ref: ${{ needs.matrix_prep.outputs.build-sha1 }}
+          fetch-depth: 0 # fetch all history; much faster for self-hosted runners
+          clean: false # true is default. it *will* delete the hosts /dev if mounted inside.
+
+      # clone the userpatches repo (`armbian/os`)
+      - name: "Checkout userpatches repo: ${{env.USERPATCHES_REPOSITORY}}#${{env.USERPATCHES_REF}}"
+        uses: actions/checkout@v3
+        if: ${{ ( env.USERPATCHES_REPOSITORY != '' ) && ( env.USERPATCHES_REF != '' ) }}
+        with:
+          repository: ${{ env.USERPATCHES_REPOSITORY }}
+          ref: ${{ env.USERPATCHES_REF }}
+          clean: false # true is default.
+          path: userpatches.repo
+
+      - name: "Put userpatches in place, and remove userpatches repo"
+        if: ${{ ( env.USERPATCHES_REPOSITORY != '' ) && ( env.USERPATCHES_REF != '' ) }}
+        run: |
+          mkdir -pv userpatches
+          rsync -av userpatches.repo/${{env.USERPATCHES_DIR}}/. userpatches/
+          rm -rf userpatches.repo
+
+      # Clean off output/info, if any
+      - name: Cleanup output/info
+        run: |
+          rm -rfv output/info
+          mkdir -pv output
+
+      # Download the artifacts (output/info) produced by the prepare-matrix job.
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: build-info-json
+          path: output/info
+
+      # List the artifacts we downloaded
+      - name: List artifacts
+        run: |
+          ls -laht output/info
+
+      - name: Import GPG key from GitHub secrets
+        id: import_gpg
+        uses: crazy-max/ghaction-import-gpg@72b6676b71ab476b77e676928516f6982eef7a41 # v5.3.0 # https://github.com/crazy-max/ghaction-import-gpg/releases
+        with:
+          gpg_private_key: ${{ secrets.REPO_GPG_PRIVATE_KEY }}
+          passphrase: ${{ secrets.REPO_GPG_PASSPHRASE }}
+
+      - name: Show GPG user IDs
+        run: |
+          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
+          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
+          echo "name:        ${{ steps.import_gpg.outputs.name }}"
+          echo "email:       ${{ steps.import_gpg.outputs.email }}"
+
+      - name: List loaded keys keys
+        run: gpg -K || true
+
+      #- name: restart repo from scratch
+      #  run: |
+      #    sudo rm -rf /opt/armbian_repo
+
+      - name: create and ensure ownership of /opt/armbian_repo
+        run: |
+          sudo mkdir -pv /opt/armbian_repo
+          sudo chown -R $USER:$USER /opt/armbian_repo
+
+      - name: copy the reprepro db inside armbian output/reprepro-db
+        run: |
+          
+          mkdir -pv output/reprepro-db/db
+          if [[ -d /opt/armbian_repo/db ]]; then
+            cp -pv /opt/armbian_repo/db/packages.db output/reprepro-db/db/packages.db
+          else
+            rm -rf output/reprepro-db
+          fi
+          
+
+      - name: Integrated reprepro-based deb-download and reprepro script generation
+        id: rolling-repo-reprepro-download-script
+        run: |
+          bash ./compile.sh airwaves-os debs-to-repo-rolling-reprepro REPO_REPREPRO_PATH=/armbian/output/reprepro-db REPO_GPG_KEYID="${{ steps.import_gpg.outputs.keyid }}" BETA=${{ github.event.inputs.nightly || 'yes' }} ${{env.EXTRA_PARAMS_ALL_BUILDS}} OCI_TARGET_BASE=${{env.OCI_TARGET_BASE}}
+
+      - name: "Logs debs-to-repo-rolling-reprepro: ${{ steps.rolling-repo-reprepro-download-script.outputs.logs_url }}"
+        run: |
+          echo "Logs debs-to-repo-rolling-reprepro: ${{ steps.rolling-repo-reprepro-download-script.outputs.logs_url }}"
+
+      #- name: Prepare the reprepro scripts
+      #  id: prepare-scripts-reprepro
+      #  run: |
+      #    bash ./compile.sh airwaves-os debs-to-repo-reprepro BETA=${{ github.event.inputs.nightly || 'yes' }} ${{env.EXTRA_PARAMS_ALL_BUILDS}}
+      #
+      #- name: "Logs debs-to-repo-reprepro: ${{ steps.prepare-scripts-reprepro.outputs.logs_url }}"
+      #  run: |
+      #    echo "Logs debs-to-repo-reprepro: ${{ steps.prepare-scripts-reprepro.outputs.logs_url }}"
+
+      - name: Run the reprepro scripts
+        id: run-scripts-reprepro
+        env:
+          REPO_GPG_KEYID: ${{ steps.import_gpg.outputs.keyid }}
+          REPO_LOCATION: /opt/armbian_repo
+          REPO_CONF_LOCATION: /opt/armbian_repo/conf
+        run: |
+          set -x
+          export REPREPRO_INFO_DIR="$(pwd)/output/info/reprepro"
+          # rpardini is an absolute idiot, and chose "[" (bracket) as the delimiter jinja template, so now has to escape it (raw/endraw). Imbecile.
+          if [[ "${{ github.event.inputs.nightly || 'yes' }}" == "yes" ]]; then
+            export INCOMING_DEBS_DIR="$(pwd)/output/debs-beta"
+          else
+            export INCOMING_DEBS_DIR="$(pwd)/output/debs"
+          fi
+          bash -x output/info/reprepro/reprepro.sh
+
+      - name: export the GPG public key from the agent into repo files
+        run: |
+          rm -fv /opt/armbian_repo/armbian-next.gpg
+          gpg --batch --export --output /opt/armbian_repo/armbian-next.gpg "${{ steps.import_gpg.outputs.keyid }}"
+          rm -fv /opt/armbian_repo/armbian-next.asc
+          gpg --batch --export --output /opt/armbian_repo/armbian-next.asc --armor "${{ steps.import_gpg.outputs.keyid }}"
+
+
+      - name: Deploy nginx and setup for serving the repo over http 8081
+        run: |
+          if [ ! -e /usr/sbin/nginx ]; then
+            sudo apt-get update
+            sudo apt-get install -y nginx-full
+          fi
+          cat <<EOF | sudo tee /etc/nginx/sites-enabled/armbian_repo.conf
+          server {
+            listen 8081;
+            access_log /var/log/nginx/repo-access.log;
+            error_log /var/log/nginx/repo-error.log;
+            location / {
+              root /opt/armbian_repo;
+              autoindex on;
+            }
+            location ~ /(.*)/conf {
+              deny all;
+            }
+            location ~ /(.*)/db {
+              deny all;
+            }
+          }
+          EOF
+          sudo nginx -t
+          sudo systemctl restart nginx
+
+      - name: Run the OCI-tagging script
+        id: run-scripts-oci-tagging
+        run: |
+          
+          set -x
+          [[ ! -f /usr/local/bin/oras ]] &&  wget -O- "https://github.com/oras-project/oras/releases/download/v1.0.1/oras_1.0.1_linux_arm64.tar.gz" | sudo tar xzf - -C/usr/local/bin/ && oras version
+          bash -x output/info/reprepro/oci_tag_versions.sh
+          
+
+
+# # Generate priv
+# gpg --batch --passphrase "supersecretpassphrase" --quick-generate-key "armbian-next (apt) <apt-repo@next.armbian.com>" default default never
+#
+# # Export priv
+# gpg --batch --pinentry-mode=loopback --yes --passphrase "supersecretpassphrase" --armor --output apt-repo-private.asc --export-secret-key
+#
+# # Put contents of apt-repo-private.asc in secret REPO_GPG_PRIVATE_KEY
+# # Put supersecretpassphrase in secret REPO_GPG_PASSPHRASE
